<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DTOs\" />
    <Folder Include="Interfaces\" />
    <Folder Include="UseCases\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Transport.Domain\Transport.Domain.csproj" />
    <ProjectReference Include="..\Transport.Shared\Transport.Shared.csproj" />
  </ItemGroup>

</Project>
